version: '3.8'
services:
  backend:
    build: ./backend
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://zentasker:password@db:5432/zentasker

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: zentasker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zentasker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
